version: '3.9'

services:
  app:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/config
      - .db_data/db.sqlite3:/db.sqlite3
    ports:
      - "8000:8000"
    env_file:
    - .env