# Generated by Django 5.0.2 on 2024-02-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='category',
        ),
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.ManyToManyField(to='tours.category'),
        ),
    ]
