# Generated by Django 5.0.2 on 2024-02-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_category_options_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='season',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter'), ('Spring', 'Spring'), ('Autumn', 'Autumn')], default='Summer', max_length=10),
        ),
    ]
